const PDFDocument = require('pdfkit');
const fs = require('fs');

const isHeading = (line) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.length > 70) return false;
  if (trimmed === trimmed.toUpperCase() && trimmed.length > 2 && trimmed.length < 50) return true;
  if (/^(Chapter|Section|Topic|Unit|Part|Module|Introduction|Conclusion|Summary|Overview|Note|Example|Definition|Theorem|Proof|Lemma|Problem|Solution|Q\.|Question)\s*/i.test(trimmed)) return true;
  if (/^[A-Z][^.!?]{2,40}:$/.test(trimmed)) return true;
  if (/^\d+[\.\)]\s+[A-Z][a-z]/.test(trimmed) && trimmed.length < 50) return true;
  return false;
};

const isBullet = (line) => {
  return /^[\-\*\•]\s+/.test(line.trim()) || /^\d+[\.\)]\s+/.test(line.trim());
};

const drawHeader = (doc, pageNum, totalPages) => {
  // Dark blue gradient header
  doc.rect(0, 0, doc.page.width, 64).fill('#1a73e8');
  doc.rect(0, 48, doc.page.width, 16).fill('#1557b0');

  // App name
  doc.fillColor('white')
     .fontSize(24)
     .font('Helvetica-Bold')
     .text('NoteLens', 72, 14, { continued: false });

  // Tagline
  doc.fillColor('rgba(255,255,255,0.75)')
     .fontSize(10)
     .font('Helvetica')
     .text('Handwritten Notes → Digital PDF', 72, 40);

  // Page number top right
  if (totalPages > 1) {
    doc.fillColor('white')
       .fontSize(10)
       .font('Helvetica')
       .text(`${pageNum} / ${totalPages}`, doc.page.width - 100, 26, { width: 60, align: 'right' });
  }

  // Date
  doc.fillColor('rgba(255,255,255,0.6)')
     .fontSize(8)
     .text(
       new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }),
       doc.page.width - 160, 42, { width: 120, align: 'right' }
     );
};

const drawFooter = (doc, pageNum, totalPages) => {
  const y = doc.page.height - 36;
  doc.rect(0, y - 4, doc.page.width, 40).fill('#f8f9fa');
  doc.strokeColor('#e0e0e0').lineWidth(0.5)
     .moveTo(0, y - 4).lineTo(doc.page.width, y - 4).stroke();
  doc.fillColor('#999').fontSize(8).font('Helvetica')
     .text(
       `Generated by NoteLens  •  Page ${pageNum} of ${totalPages}  •  ${new Date().toLocaleString('en-IN')}`,
       0, y + 6, { align: 'center' }
     );
};

const renderStyledText = (doc, text, startY) => {
  const lines = text.split('\n');
  const contentWidth = doc.page.width - 144;
  let prevType = 'none';

  lines.forEach((line) => {
    const trimmed = line.trim();

    // Empty line
    if (!trimmed) {
      doc.moveDown(0.3);
      prevType = 'empty';
      return;
    }

    // Page separator
    if (trimmed.startsWith('---')) {
      doc.moveDown(1);
      doc.rect(72, doc.y, contentWidth, 28).fillAndStroke('#e8f0fe', '#c5d8fc');
      doc.fillColor('#1a73e8').fontSize(12).font('Helvetica-Bold')
         .text(trimmed.replace(/---/g, '').trim() || 'Page', 80, doc.y - 22, { width: contentWidth - 16, align: 'center' });
      doc.moveDown(0.8);
      prevType = 'separator';
      return;
    }

    // Heading
    if (isHeading(trimmed)) {
      if (prevType !== 'none' && prevType !== 'separator') doc.moveDown(0.8);
      const headingY = doc.y;
      doc.rect(72, headingY - 3, contentWidth, 24).fill('#e8f0fe');
      doc.rect(72, headingY - 3, 4, 24).fill('#1a73e8');
      doc.fillColor('#1557b0').fontSize(13).font('Helvetica-Bold')
         .text(trimmed, 84, headingY + 2, { width: contentWidth - 16 });
      doc.moveDown(0.5);
      prevType = 'heading';
      return;
    }

    // Bullet point
    if (isBullet(trimmed)) {
      if (prevType === 'none' || prevType === 'heading') doc.moveDown(0.2);
      const bulletText = trimmed.replace(/^[\-\*\•\d+\.\)]\s+/, '');
      const bulletY = doc.y;
      doc.circle(84, bulletY + 5, 2.5).fill('#1a73e8');
      doc.fillColor('#333').fontSize(11).font('Helvetica')
         .text(bulletText, 94, bulletY, { width: contentWidth - 22, lineGap: 3 });
      doc.moveDown(0.25);
      prevType = 'bullet';
      return;
    }

    // Normal paragraph
    if (prevType === 'heading') doc.moveDown(0.2);
    else if (prevType === 'bullet') doc.moveDown(0.3);
    doc.fillColor('#1a1a1a').fontSize(11).font('Helvetica')
       .text(trimmed, 72, doc.y, {
         width: contentWidth,
         lineGap: 5,
         align: 'justify',
         paragraphGap: 4
       });
    doc.moveDown(0.3);
    prevType = 'paragraph';
  });
};

const embedImage = (doc, imagePath, maxHeight = 240) => {
  if (!imagePath || !fs.existsSync(imagePath)) return;

  const contentWidth = doc.page.width - 144;

  // Image container box
  doc.rect(72, doc.y, contentWidth, maxHeight + 24)
     .fillAndStroke('#f8f9fa', '#e8eaed');

  // Image label
  doc.fillColor('#888').fontSize(8).font('Helvetica-Bold')
     .text('ORIGINAL SCAN', 80, doc.y - maxHeight - 18, { characterSpacing: 1 });

  try {
    doc.image(imagePath, 80, doc.y - maxHeight - 4, {
      fit: [contentWidth - 16, maxHeight - 8],
      align: 'center',
      valign: 'center'
    });
  } catch (e) {
    doc.fillColor('#aaa').fontSize(10)
       .text('Image could not be embedded', 72, doc.y - maxHeight / 2, { align: 'center' });
  }

  doc.moveDown(1.5);
};

const generatePDF = async (text, title, imagePath, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 90, bottom: 60, left: 72, right: 72 },
        info: { Title: title, Author: 'NoteLens', Subject: 'Digitized Notes' },
        bufferPages: true
      });

      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);

      drawHeader(doc, 1, 1);
      doc.y = 90;

      // Title section
      doc.fillColor('#1a1a1a').fontSize(20).font('Helvetica-Bold')
         .text(title.replace(/_/g, ' ').replace(/\d{13,}/g, '').trim(), 72, doc.y, {
           width: doc.page.width - 144, align: 'center'
         });
      doc.moveDown(0.3);

      // Thin accent line
      doc.rect(72, doc.y, doc.page.width - 144, 3).fill('#1a73e8');
      doc.moveDown(1.2);

      // Stats row
      const wordCount = text.split(/\s+/).filter(w => w.length > 0).length;
      const lineCount = text.split('\n').filter(l => l.trim()).length;
      doc.rect(72, doc.y, doc.page.width - 144, 36).fill('#f1f3f4');
      doc.fillColor('#555').fontSize(10).font('Helvetica')
         .text(`📝  ${wordCount} words   |   📄  ${lineCount} lines   |   🕐  ${new Date().toLocaleTimeString('en-IN')}`,
           80, doc.y - 28, { width: doc.page.width - 160, align: 'center' });
      doc.moveDown(1.2);

      // Original image
      if (imagePath && fs.existsSync(imagePath)) {
        embedImage(doc, imagePath, 240);
      }

      // Section label
      doc.rect(72, doc.y, doc.page.width - 144, 28).fill('#1a73e8');
      doc.fillColor('white').fontSize(11).font('Helvetica-Bold')
         .text('DIGITIZED TEXT', 80, doc.y - 20, {
           width: doc.page.width - 160, align: 'left', characterSpacing: 1.5
         });
      doc.moveDown(0.8);

      // Render text
      renderStyledText(doc, text);

      drawFooter(doc, 1, 1);
      doc.end();

      writeStream.on('finish', () => resolve(outputPath));
      writeStream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

const generateMultiPagePDF = async (pages, title, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const total = pages.length;
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 90, bottom: 60, left: 72, right: 72 },
        info: { Title: title, Author: 'NoteLens' },
        bufferPages: true
      });

      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);

      pages.forEach((page, index) => {
        if (index > 0) doc.addPage();

        drawHeader(doc, index + 1, total);
        doc.y = 90;

        // Page title
        doc.fillColor('#1a1a1a').fontSize(18).font('Helvetica-Bold')
           .text(`Page ${index + 1}`, 72, doc.y, { width: doc.page.width - 144, align: 'center' });
        doc.moveDown(0.3);
        doc.rect(72, doc.y, doc.page.width - 144, 3).fill('#1a73e8');
        doc.moveDown(1.2);

        // Stats
        const wordCount = (page.text || '').split(/\s+/).filter(w => w.length > 0).length;
        doc.rect(72, doc.y, doc.page.width - 144, 36).fill('#f1f3f4');
        doc.fillColor('#555').fontSize(10).font('Helvetica')
           .text(`📝  ${wordCount} words   |   🎯  ${page.confidence || 90}% accuracy`,
             80, doc.y - 28, { width: doc.page.width - 160, align: 'center' });
        doc.moveDown(1.2);

        // Image
        if (page.imagePath && fs.existsSync(page.imagePath)) {
          embedImage(doc, page.imagePath, 220);
        }

        // Text section label
        doc.rect(72, doc.y, doc.page.width - 144, 28).fill('#1a73e8');
        doc.fillColor('white').fontSize(11).font('Helvetica-Bold')
           .text('DIGITIZED TEXT', 80, doc.y - 20, {
             width: doc.page.width - 160, align: 'left', characterSpacing: 1.5
           });
        doc.moveDown(0.8);

        renderStyledText(doc, page.text || 'No text detected on this page.');
        drawFooter(doc, index + 1, total);
      });

      doc.end();
      writeStream.on('finish', () => resolve(outputPath));
      writeStream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDF, generateMultiPagePDF };