const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a styled PDF from extracted OCR text
 */
const generatePDF = async (text, title, imagePath, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margins: { top: 60, bottom: 60, left: 72, right: 72 },
        info: {
          Title: title,
          Author: 'TextLens App',
          Subject: 'OCR Extracted Text',
          Creator: 'TextLens - Handwriting to Digital Text'
        }
      });

      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);

      // ─── Header ───────────────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 50).fill('#1a73e8');
      doc.fillColor('white')
         .fontSize(20)
         .font('Helvetica-Bold')
         .text('📄 TextLens', 72, 15, { align: 'left' });

      doc.fillColor('white')
         .fontSize(10)
         .font('Helvetica')
         .text(`Generated: ${new Date().toLocaleString()}`, 0, 20, { align: 'right' });

      doc.moveDown(2);

      // ─── Title Section ────────────────────────────────────────
      doc.fillColor('#1a73e8')
         .fontSize(22)
         .font('Helvetica-Bold')
         .text(title, { align: 'center' });

      doc.moveDown(0.5);

      doc.strokeColor('#1a73e8')
         .lineWidth(2)
         .moveTo(72, doc.y)
         .lineTo(doc.page.width - 72, doc.y)
         .stroke();

      doc.moveDown(1);

      // ─── Original Image Section ────────────────────────────────
      if (imagePath && fs.existsSync(imagePath)) {
        doc.fillColor('#555')
           .fontSize(11)
           .font('Helvetica-Bold')
           .text('ORIGINAL IMAGE', { align: 'left' });

        doc.moveDown(0.3);

        try {
          const imgWidth = doc.page.width - 144;
          const maxImgHeight = 250;

          doc.image(imagePath, {
            fit: [imgWidth, maxImgHeight],
            align: 'center'
          });
        } catch (imgError) {
          doc.fillColor('#999').fontSize(10).text('[Image could not be embedded]');
        }

        doc.moveDown(1);

        // Divider
        doc.strokeColor('#ddd')
           .lineWidth(1)
           .moveTo(72, doc.y)
           .lineTo(doc.page.width - 72, doc.y)
           .stroke();

        doc.moveDown(1);
      }

      // ─── Extracted Text Section ────────────────────────────────
      doc.fillColor('#555')
         .fontSize(11)
         .font('Helvetica-Bold')
         .text('EXTRACTED TEXT (DIGITIZED)', { align: 'left' });

      doc.moveDown(0.5);

      // Background box for text
      const textStartY = doc.y;
      const textBoxPadding = 12;

      doc.fillColor('#f8f9fa')
         .roundedRect(
           72 - textBoxPadding,
           textStartY - textBoxPadding,
           doc.page.width - 144 + textBoxPadding * 2,
           Math.max(text.split('\n').length * 18 + textBoxPadding * 2, 60),
           5
         )
         .fill();

      // Actual text
      doc.fillColor('#212121')
         .fontSize(12)
         .font('Helvetica')
         .text(text || 'No text was detected in the image.', 72, textStartY, {
           align: 'left',
           lineGap: 5,
           width: doc.page.width - 144
         });

      doc.moveDown(2);

      // ─── Stats Section ─────────────────────────────────────────
      const wordCount = text.split(/\s+/).filter(w => w.length > 0).length;
      const charCount = text.length;
      const lineCount = text.split('\n').length;

      doc.fillColor('#555')
         .fontSize(9)
         .font('Helvetica')
         .text(`Words: ${wordCount}  |  Characters: ${charCount}  |  Lines: ${lineCount}`, {
           align: 'center',
           color: '#888'
         });

      // ─── Footer ───────────────────────────────────────────────
      const footerY = doc.page.height - 40;
      doc.strokeColor('#eee')
         .lineWidth(1)
         .moveTo(72, footerY - 10)
         .lineTo(doc.page.width - 72, footerY - 10)
         .stroke();

      doc.fillColor('#999')
         .fontSize(8)
         .text('Generated by TextLens App • Handwriting to Digital Text Converter', 0, footerY, {
           align: 'center'
         });

      doc.end();

      writeStream.on('finish', () => resolve(outputPath));
      writeStream.on('error', reject);

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDF };
